project:
  type: website
  output-dir: docs  # needed for GitHub Pages

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo  # or whichever theme you like
  docx:
    toc: true
    number-sections: false

website:
  title: "Thesis"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
        
csl: apa.csl
bibliography: references.bib
